change place swagger

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -99,12 +99,6 @@ jobs:
             docker exec -it newimage sh -c "cd /var/www/html && php bin/magento cache:flush"
             docker exec -it newimage sh -c "cd /var/www/html && php bin/magento setup:di:compile"
       - run:
-          name: Test Swagger
-          command: | 
-            apt-get -y install curl
-            response=$(curl -s -o /dev/null -I -w "%{http_code}" http://stg-magento2.mundipagg.com/rest/all/schema?services=all)
-            if [ "$response" = '200' ]; then echo 'Swagger Ok'; else echo 'Swagger invalid'; exit 1; fi
-      - run:
           name: Clear useless files
           command: |
             pwd
@@ -121,6 +115,11 @@ jobs:
   deploy_staging:
      machine: true
      steps:
+       - run:
+           name: Test Swagger
+           command: | 
+             response=$(curl -s -o /dev/null -I -w "%{http_code}" http://stg-magento2.mundipagg.com/rest/all/schema?services=all)
+             if [ "$response" = '200' ]; then echo 'Swagger Ok'; else echo 'Swagger invalid'; exit 1; fi
        - run:
            name: Send deployment webhook to Rancher
            command: |
