Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -53,30 +53,7 @@ jobs:
              docker exec -it newimage ls
              docker exec -it newimage sh -c "mkdir /app/tmp"
              docker cp /app/wait-for-mysql.sh newimage:app/tmp/
-             docker cp /app/magento2_module_install.sql newimage:app/tmp/
-      - run:
-          name: Install and run Functional Tests dependencies
-          command: |
-            docker exec -i newimage sh -c \
-              "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
-              echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list && \
-              apt-get -y update && apt-get -y install google-chrome-unstable"
-            
-            docker exec -it newimage sh -c "git clone https://github.com/mundipagg/ecommerce-test-package.git /behat-test"
-              
-            docker exec -it newimage sh -c "cd /behat-test && rm -rf composer.lock && rm -rf failureScreenshots"
-                                    
-            docker exec -it newimage sh -c "composer config -g github-oauth.github.com ${GIT_HUB_AUTH}"
-             
-            docker exec -it newimage sh -c "cd /behat-test && composer install --prefer-dist"
-              
-            docker exec --detach newimage google-chrome-unstable --disable-gpu --no-sandbox --headless --remote-debugging-address=127.0.0.1 --remote-debugging-port=9222 --disable-extensions -user-data-dir=/tmp/test
-
-            docker exec -it newimage bash -c "cd /behat-test && printf 'BASE_URL=\"https://stg-magento2.mundipagg.com/\"' > .env"
-          
-            docker exec -it newimage sh -c "cd /behat-test && vendor/bin/behat --profile magento2"
-                       
-            docker exec -it newimage sh -c "if [ -d /behat-test/failureScreenshots ]; then echo 'Behat fail'; exit 1; else echo 'Behat OK'; fi"
+             docker cp /app/magento2_module_install.sql newimage:app/tmp/     
       - run:
           name: Activate and setup Plugin
           command: |
@@ -113,6 +90,29 @@ jobs:
 
             docker exec -it newimage sh -c "cd /var/www/html && php bin/magento cache:flush"
             docker exec -it newimage sh -c "cd /var/www/html && php bin/magento setup:di:compile"
+      - run:
+          name: Install and run Functional Tests dependencies
+          command: |
+            docker exec -i newimage sh -c \
+              "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
+              echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | tee /etc/apt/sources.list.d/google-chrome.list && \
+              apt-get -y update && apt-get -y install google-chrome-unstable"
+            
+            docker exec -it newimage sh -c "git clone https://github.com/mundipagg/ecommerce-test-package.git /behat-test"
+              
+            docker exec -it newimage sh -c "cd /behat-test && rm -rf composer.lock && rm -rf failureScreenshots"
+                                    
+            docker exec -it newimage sh -c "composer config -g github-oauth.github.com ${GIT_HUB_AUTH}"
+             
+            docker exec -it newimage sh -c "cd /behat-test && composer install --prefer-dist"
+              
+            docker exec --detach newimage google-chrome-unstable --disable-gpu --no-sandbox --headless --remote-debugging-address=127.0.0.1 --remote-debugging-port=9222 --disable-extensions -user-data-dir=/tmp/test
+
+            docker exec -it newimage bash -c "cd /behat-test && printf 'BASE_URL=\"https://localhost/\"' > .env"
+          
+            docker exec -it newimage sh -c "cd /behat-test && vendor/bin/behat --profile magento2"
+                       
+            docker exec -it newimage sh -c "if [ -d /behat-test/failureScreenshots ]; then echo 'Behat fail'; exit 1; else echo 'Behat OK'; fi"      
       - run:
           name: Clear useless files
           command: |
